insert into words (id_category, word) values (2, "Furious Gaming");
insert into words (id_category, word) values (2, "Pineapple Express");
insert into words (id_category, word) values (2, "Isurus Gaming");
insert into words (id_category, word) values (2, "XIS eSports Club");
insert into words (id_category, word) values (2, "Royal Paladin eSports");
insert into words (id_category, word) values (2, "No Team");
insert into words (id_category, word) values (2, "Little Wraith");
insert into words (id_category, word) values (2, "Team Dignitas OCE");
insert into words (id_category, word) values (2, "Avant Garde Redemption");
insert into words (id_category, word) values (2, "Team Immunity");
insert into words (id_category, word) values (2, "Avant Garde");
insert into words (id_category, word) values (2, "SK Gaming Prime");
insert into words (id_category, word) values (2, "Revolt Gentlemen E-Sports Club EUW");
insert into words (id_category, word) values (2, "Reason Gaming");
insert into words (id_category, word) values (2, "LowLandLions");
insert into words (id_category, word) values (2, "mYinsanity");
insert into words (id_category, word) values (2, "Evil Geniuses");
insert into words (id_category, word) values (2, "Dimegio Club");
insert into words (id_category, word) values (2, "CNB e-Sports Club");
insert into words (id_category, word) values (2, "Keyd Stars");
insert into words (id_category, word) values (2, "KaBuM! e-Sports");
insert into words (id_category, word) values (2, "Team UNITED");
insert into words (id_category, word) values (2, "Keyd Team");
insert into words (id_category, word) values (2, "paiN Gaming");
insert into words (id_category, word) values (2, "Rising On Gaming");
insert into words (id_category, word) values (2, "Insight eSports");
insert into words (id_category, word) values (2, "Cyber Gamer e-Sports");
insert into words (id_category, word) values (2, "Team awp");
insert into words (id_category, word) values (2, "Bulgaria's Finest");
insert into words (id_category, word) values (2, "Obicham Pyrjoli");
insert into words (id_category, word) values (2, "Copenhagen Wolves");
insert into words (id_category, word) values (2, "Cloud 9 Tempest");
insert into words (id_category, word) values (2, "Counter Logic Gaming");
insert into words (id_category, word) values (2, "Gold Gaming LA");
insert into words (id_category, word) values (2, "Team Summon");
insert into words (id_category, word) values (2, "vVv Gaming Red");
insert into words (id_category, word) values (2, "Curse Academy");
insert into words (id_category, word) values (2, "Falafel Gaming");
insert into words (id_category, word) values (2, "Team 8");
insert into words (id_category, word) values (2, "Team LoLPro");
insert into words (id_category, word) values (2, "compLexity.Red");
insert into words (id_category, word) values (2, "Team Coast");
insert into words (id_category, word) values (2, "Team Dignitas");
insert into words (id_category, word) values (2, "Team SoloMid");
insert into words (id_category, word) values (2, "ChiLeanFivE The Legacy");
insert into words (id_category, word) values (2, "Royal Paladin eSports Eclipse");
insert into words (id_category, word) values (2, "ChiLeanFivE Hopes");
insert into words (id_category, word) values (2, "Kaos Latin Gamers");
insert into words (id_category, word) values (2, "LMQ");
insert into words (id_category, word) values (2, "OMG");
insert into words (id_category, word) values (2, "Positive Energy");
insert into words (id_category, word) values (2, "Royal Club");
insert into words (id_category, word) values (2, "Team WE");
insert into words (id_category, word) values (2, "Edward Gaming");
insert into words (id_category, word) values (2, "Vici Gaming");
insert into words (id_category, word) values (2, "Dirt Nap Gaming");
insert into words (id_category, word) values (2, "STAR");
insert into words (id_category, word) values (2, "Invictus Gaming");
insert into words (id_category, word) values (2, "Manila Eagles");
insert into words (id_category, word) values (2, "LGD Gaming");
insert into words (id_category, word) values (2, "Team WE Academy");
insert into words (id_category, word) values (2, "Young Glory");
insert into words (id_category, word) values (2, "Team DK");
insert into words (id_category, word) values (2, "Ninjas in Pyjamas");
insert into words (id_category, word) values (2, "Alliance");
insert into words (id_category, word) values (2, "CJ Gaming");
insert into words (id_category, word) values (2, "SK Gaming");
insert into words (id_category, word) values (2, "Eternity Gaming");
insert into words (id_category, word) values (2, "SUPA HOT CREW");
insert into words (id_category, word) values (2, "n!faculty");
insert into words (id_category, word) values (2, "The Fox Sound");
insert into words (id_category, word) values (2, "Cloud 9 Eclipse");
insert into words (id_category, word) values (2, "Reign eSports");
insert into words (id_category, word) values (2, "Fnatic");
insert into words (id_category, word) values (2, "RCTIC eSports");
insert into words (id_category, word) values (2, "");
insert into words (id_category, word) values (2, "Team ALTERNATE");
insert into words (id_category, word) values (2, "ThunderBot");
insert into words (id_category, word) values (2, "Gamers 2");
insert into words (id_category, word) values (2, "COREPLAY");
insert into words (id_category, word) values (2, "mousesports");
insert into words (id_category, word) values (2, "PENTA Sports");
insert into words (id_category, word) values (2, "Japanese Anti Virus Junior");
insert into words (id_category, word) values (2, "Millenium");
insert into words (id_category, word) values (2, "ESC Gaming Europe");
insert into words (id_category, word) values (2, "Tick Trick and Duck");
insert into words (id_category, word) values (2, "Team Server-Forge");
insert into words (id_category, word) values (2, "[[Team Rage]]");
insert into words (id_category, word) values (2, "Test Your Limits");
insert into words (id_category, word) values (2, "CGA LEGENDs");
insert into words (id_category, word) values (2, "Energy Pacemaker.HK");
insert into words (id_category, word) values (2, "Energy Pacemaker.YCSM");
insert into words (id_category, word) values (2, "Stand Point Gaming");
insert into words (id_category, word) values (2, "HK Attitude");
insert into words (id_category, word) values (2, "Roaring Agony");
insert into words (id_category, word) values (2, "IceLanD");
insert into words (id_category, word) values (2, "Unicorns of Love");
insert into words (id_category, word) values (2, "compLexity Gaming");
insert into words (id_category, word) values (2, "N/A");
insert into words (id_category, word) values (2, "inFerno eSports");
insert into words (id_category, word) values (2, "Team Coast Gold");
insert into words (id_category, word) values (2, "None");
insert into words (id_category, word) values (2, "COGnitive Gaming");
insert into words (id_category, word) values (2, "Team Ultra Vires");
insert into words (id_category, word) values (2, "Invaders");
insert into words (id_category, word) values (2, "Kuala Lumpur Hunters");
insert into words (id_category, word) values (2, "Work in Progress");
insert into words (id_category, word) values (2, "MTK eSports");
insert into words (id_category, word) values (2, "Druidz E-Sport Europe");
insert into words (id_category, word) values (2, "vVv Gaming White");
insert into words (id_category, word) values (2, "BrawL");
insert into words (id_category, word) values (2, "Seven Wars Lyon");
insert into words (id_category, word) values (2, "No Remorse eSports");
insert into words (id_category, word) values (2, "Imperium Pro Team");
insert into words (id_category, word) values (2, "Mineski");
insert into words (id_category, word) values (2, "Team ROCK");
insert into words (id_category, word) values (2, "Team ROCCAT");
insert into words (id_category, word) values (2, "Denial eSports.EU");
insert into words (id_category, word) values (2, "Planetkey Dynamics");
insert into words (id_category, word) values (2, "neXtPlease! Gaming");
insert into words (id_category, word) values (2, "Gambit Gaming");
insert into words (id_category, word) values (2, "RoX");
insert into words (id_category, word) values (2, "Good Team Multigaming");
insert into words (id_category, word) values (2, "Insidious Gaming");
insert into words (id_category, word) values (2, "Singapore Sentinels");
insert into words (id_category, word) values (2, "Taipei Assassins");
insert into words (id_category, word) values (2, "Insidious Gaming Rebirth");
insert into words (id_category, word) values (2, "Insidious Gaming Exile");
insert into words (id_category, word) values (2, "Incredible Miracle 2");
insert into words (id_category, word) values (2, "Samsung Galaxy Blue");
insert into words (id_category, word) values (2, "NaJin Black Sword");
insert into words (id_category, word) values (2, "Xenics Storm");
insert into words (id_category, word) values (2, "CJ Entus Blaze");
insert into words (id_category, word) values (2, "KT Rolster Arrows");
insert into words (id_category, word) values (2, "SK Telecom T1 S");
insert into words (id_category, word) values (2, "SK Telecom T1 K");
insert into words (id_category, word) values (2, "Xenics Blast");
insert into words (id_category, word) values (2, "UBC eSports");
insert into words (id_category, word) values (2, "CJ Entus Frost");
insert into words (id_category, word) values (2, "Jin Air Green Wings Stealths");
insert into words (id_category, word) values (2, "Samsung Galaxy Ozone");
insert into words (id_category, word) values (2, "Team Hunters");
insert into words (id_category, word) values (2, "NEB");
insert into words (id_category, word) values (2, "SuperStar");
insert into words (id_category, word) values (2, "Jin Air Green Wings Falcons");
insert into words (id_category, word) values (2, "NeL");
insert into words (id_category, word) values (2, "Little Hippo");
insert into words (id_category, word) values (2, "NaJin White Shield");
insert into words (id_category, word) values (2, "none");
insert into words (id_category, word) values (2, "Maximum impact Gaming Wicked");
insert into words (id_category, word) values (2, "Team Olympus");
insert into words (id_category, word) values (2, "MVP Blue");
insert into words (id_category, word) values (2, "KT Rolster Bullets");
insert into words (id_category, word) values (2, "Team NB");
insert into words (id_category, word) values (2, "MKZ");
insert into words (id_category, word) values (2, "Incredible Miracle");
insert into words (id_category, word) values (2, "Chunnam Techno University");
insert into words (id_category, word) values (2, "NaJin Shield");
insert into words (id_category, word) values (2, "NaJin e-mFire");
insert into words (id_category, word) values (2, "Incredible Miracle 1");
insert into words (id_category, word) values (2, "VTG Monsters");
insert into words (id_category, word) values (2, "OverGaming");
insert into words (id_category, word) values (2, "Karont3 e-Sports Club");
insert into words (id_category, word) values (2, "GIANTS! Gaming");
insert into words (id_category, word) values (2, "HK Attitude Mage");
insert into words (id_category, word) values (2, "Taipei Snipers");
insert into words (id_category, word) values (2, "ahq e-Sports Club");
insert into words (id_category, word) values (2, "HK Attitude Priest");
insert into words (id_category, word) values (2, "Garena Team");
insert into words (id_category, word) values (2, "Machi E-Sports");
insert into words (id_category, word) values (2, "ahq Fighter");
insert into words (id_category, word) values (2, "yoe Flash Wolves Junior");
insert into words (id_category, word) values (2, "yoe Flash Wolves");
insert into words (id_category, word) values (2, "Team Ozone Taiwan");
insert into words (id_category, word) values (2, "MiTH Flashdive");
insert into words (id_category, word) values (2, "Bangkok Titans");
insert into words (id_category, word) values (2, "Team Infinite");
insert into words (id_category, word) values (2, "Always With Honor");
insert into words (id_category, word) values (2, "GameEkstra");
insert into words (id_category, word) values (2, "HWA Gaming");
insert into words (id_category, word) values (2, "Dark Passage");
insert into words (id_category, word) values (2, "Team Turquality");
insert into words (id_category, word) values (2, "ATLAS eSports Team");
insert into words (id_category, word) values (2, "Wild Fire e-Sports Club");
insert into words (id_category, word) values (2, "Instruments of Surrender");
insert into words (id_category, word) values (2, "Animate eSports");
insert into words (id_category, word) values (2, "FM eSports");
insert into words (id_category, word) values (2, "Team Infused");
insert into words (id_category, word) values (2, "Aware Gaming");
insert into words (id_category, word) values (2, "UC San Diego");
insert into words (id_category, word) values (2, "Cloud 9");
insert into words (id_category, word) values (2, "Team Curse");
insert into words (id_category, word) values (2, "High Rollers Gaming");
insert into words (id_category, word) values (2, "ZeBopSquad");
insert into words (id_category, word) values (2, "Team TowerDiveTV");
insert into words (id_category, word) values (2, "No Dice Gaming");
insert into words (id_category, word) values (2, "XDG Gaming");
insert into words (id_category, word) values (2, "New World Eclipse");
insert into words (id_category, word) values (2, "Team Astral Poke");
insert into words (id_category, word) values (2, "The Salad Bar");
insert into words (id_category, word) values (2, "Infinite Odds");
insert into words (id_category, word) values (2, "Velocity eSports");
insert into words (id_category, word) values (2, "Team Solo Queue");
insert into words (id_category, word) values (2, "Hanoi Dragons");
insert into words (id_category, word) values (2, "Saigon Jokers");
insert into words (id_category, word) values (2, "Saigon Fantastic Five");
insert into words (id_category, word) values (2, "Hanoi Phoenix");
insert into words (id_category, word) values (2, "Beautiful Life Gaming");
insert into words (id_category, word) values (2, "Full Louis");
insert into words (id_category, word) values (2, "XGame");
	